spring:
  profiles:
    active: local
    group:
      local: local, common, secret

---

spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
server:
  port: 8080
  deploy-address: localhost
  name: local

---

spring:
  config:
    activate:
      on-profile: common
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: Naver
            authorizationGrantType: authorization_code
            client-authentication-method: POST
          kakao:
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

client:
  deploy-address: "localhost:3000"

mybatis:
  mapper-locations:
    - /mappers/*.xml